---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: petclinic-db-credentials
  namespace: sit
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgC449r3fl7in1McUmYfscIKJqGV+7+5jb69eCxN6T9boWgYGq2RXUjqA9UNX5sbOe9/ClkfRmjZa3kCdGsT2X+3FG6i4fDdnDHci+0NqiS7xsEbeNmvCloBkeCjlE9pfA6Jc//+ReCqngI2E0asNafM1k27Uu9M8PzudJH7z7Ogwu1P2ZG5EHd5texPeVpYiALd22TopGRfO2uUnGuXt3I8psBll1K7c7uGMAsp1X983bYxWLjMcctXLuzHped6QNFGDYzX0HfBHFf+Z4Xi1Hitlhnp5pOD06xqS28iXSMzJVHX9vY1Qp/L1V5LD3l9o5JPFs6fBWaHfWDW8fPBxWMd0cfWyz1Kz9b1IOTnzYqLda6YWYT3yT4Wva3i3A5+go2IBncL/E5WsPM/k67u3IEv+jI2k2pTJxt47AhZFIzst/p0DmLDnSssMwZ7mTUPa8QXA95ZPvcuQujIqaFU7G5thRZdGRQlJvhnFbrxR/egr9g84IgT6P5nZwG6ZF+GzmicgzoQLuiuOJInVYOIwWGODkqudbsrjvlzaoYJf/05Muyn6pQXcyrTEXZz2lck9RFjU+Ej3PUSy5Su71n16lv01uTINR5IjwFZzySNI4Bxr0a8GXAjt9QtjkGZ5IhxFJSxMl0nPaPpncM6LnBwjlP3FiVCPNMExgpfnLwEvZDx80Jvd8J0WcxFsY4JHHe7JkfDMWYONydkqSI=
    POSTGRES_USER: AgCsNEQ7CDWgILxZe1SPmixQj6TWnh60G5Dl8ybk+3UGwDgguzDjWQ7u9J9vIHQV/03xp2VoTfxEts4/TDiVN8Wzfxe/LIIvHMAP/FlZ/kY8R/teeAns/ePOqbWXkuS+d+2wUQs2mXYnnKvzbeiiVgmm6l4TZuvt7UwkGMCMbF+jjdP/DJFSivpYCqkap8xOFU78n8CSj/LB1N0+IkybxLMKN58BAHOo2fk+TplmBaRMhmhBpHMZ4wGK04/67FayVfrwF4ifx7/Z9M+CiEfLW75sLpoFmge7K7hlK38VAjWZC6KtbFX0AZ3lXK/Rc7VX9W+1fQ6IigT3Ez3RbaQqORWN9/KSLyiDVUJimEqAwb7XRjXMKTfu9c0DnoMI4HoCshVg12ghc55XSSZQW0DgeaKiKM6M9pm91JmaaMteeKrP5eQyDaXp5wJuL+quVKqNYOtyO/ImGTYiSb9vtpjXLRuL/ZKr5hncT+TyD8ay2k+3tO3nVtlNwc8n0KMRJeSxp4pvhTvYhqteSaPStHVD0XwE+odwvL0z/NoK/dCPO1/r9Se88yFAK+HEhFRdFBuU7JLHaLHc7SBSWY+wWpx78OMLS0lPNAwoTX60bV7ZuMXt84cIQb+f8zEKDFyasiqNn83P7IE/3TJw44VjR7Vvzux0CivxKpfZUUIhY7H+mUb4NE3+k7T+rIRActlHMMBwTlfQJ4MgiqIrsr0=
  template:
    metadata:
      name: petclinic-db-credentials
      namespace: sit
