---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: petclinic-db-credentials
  namespace: sit-bob
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCinnuaZTKZZhOUUFV188p+BO0UMI/HuvZFvmnHH/zpvCfFyiAPFgzYYk94kFd4zKj+Os3SYmUp9cwQq8c1CVmOvBsO4SmznnIaYppQ4i855FICOtpJD7Xl1VS2g2FDvec2q9Rrw/bAqHcOTVQbRBf5x7OvCPBg+fUiXKwHgXnu6knERtaBKmwRptPRYVWwZhBMzqK6EqbFzz5JO1BUhbe3+zaHHVcJMUFhA2zyNg45zIvhHtM95mO7dqc3xdgCdyS4IxbbsRDLKGMboNVFdP43oJ1yPmw7CioQ1th0XDNakFT4OFKGiUpwzY/yBXOwM6nnqKDan+6qg9OEr5Rn1yY3vGm6zXf6C2yy6f2tB56pj5ilpa/jc68q3hQtI5cfYT+bi1Iz5cHwrOmZHIX31Yp6FnJD7ckn9ep8ODU9ZOq5NLOr3WKaKRjLPXxn2vEP2Z9zNkz1OMGxmGut7PKkPtrJzpkn39nLCOZcmVd+N1/R0sGsseP9ei5V3xam7cxvvDh6fZXho7Rp6lhPvZ945ebPNllzT7u+KkrrUqGce+p836FZ0Lxas78MKXW+XvlxWIE8SzKA1s/cXc6rAfAU9MvJ1VCtpxENOs6KA2F8E8vAX0hr5EFTZgetAR3En+XmEGroYh7+/Y6NH+aKK7Nb0b/QdOkjDCceI9sqU3idUO6YG7ODAwKbW9L8u2Ze8gh4qiAvbaIDepyvu6k=
    POSTGRES_USER: AgBF/JbO2hhmYEGyogUGXpwu6VJDaIFtcBxOKUeaqnWEoVLyPToSoZcTPr0dfVRAny3oGj8GAVPi8STJkaTV6F/Bseno6ojbHexH9W0/B2L1HuLPIpz4znH5JVYHdTD6IUcviYcdEh206EVViwL4XehPlH7uXHP3Tlbu4VgGkVaHNB8W14A8A9v8OIh0mizdJB9krg4gHhCIrilaHnAUK0L+Y8MNXQB0/7mEpT6UCMFeQbiVigOJJ660e6Xr8pfzH4Tc30Km5FHOf9ql7WVh3FxtO8yqyP7f8eK/x41/AQgzXsbqd+gEEuu81wq4y4jzJsR115olwuy6L/OIrhEwqmfITeEElXt6UdDbMYaVRZrMHR/5HYcGkoU4ky/T3VyK7lRdfmpukm3/zxfBf0HB6f4wx0kITzsb59q+5S4eZ/TYwpnO/pVjTxh7qZ+0EWu10peOfkmQc41JOHEosf9BAxKhJhjgwysyYuZpCmn0yiSn5v8u+nvjFp7/RG3cA3HC5IhYGdJvcTiZpXzmvZN3qXHXCs5m94u3gDBr1zxmBnHly6i8wSuhdJz4bAEfytFpgQ/4eNNavrcYgU+Wcra3LAe2pNefB22edZvdBmYEhVGjb1vaPnNAP4KwmYpDM/aUEvk2PVYIU9kvg9KiIVx58HC7jDrU9G2g3bL9O2euYNFtUuVOqbXr0ESTX2P+t98uc3Qrk+8KhSoIqHY=
  template:
    metadata:
      name: petclinic-db-credentials
      namespace: sit-bob
