---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: petclinic-db-credentials
  namespace: pre-sit
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB93bqHsJ3XlIo600b/jJe9svgJS0A++WaZ3PZpdbWpqOZIS6+oXKLEGEoKMbYa9J8uraQF0zLObv57XujYyvLpHlRE93bRddysIjxEQ7ztkRUmDiqpsvDxRPP2R6ZqUvnxpyCmN3MlemGnHte+/8vT6ucHOxBz9tAEJvYGw7FoeBGQ/kAp7l7m/u36j1PgXKQQdPELoAO10AZElDGN7Cxm9YAvCHz4bduUzudODwwUzeLa8Ig9FD3Fvk77fi63fYHAFjH3craGVLeoD9ZUWAmgfBjsWN1pTSRbgoK8HXJyppyt2CHurqagzYzrjbN7vebe4IKSUeWcvDhKEXf6Elsml4vVy+ARuxziyz6lTkNWz1XeBME8eUrNzhwFJn+Lr/PqHRLifzTnlKbwURIqeF5X2saBiNPbJLTIi84CvzarxuCwMRRlOLxpKq6CWdIYifDcjvKie/4mhNk6k2nAjCIe2biOR80mbB8tPJn5yd1iafJS8LipQ+TrP+IZ5MMFCgsvEKdCQJmV2xJ2U4U6Ihb5rHq3+1LzxoS8jGsZGLEEqS2VWxiPX/IRhqLzSkBd1dRjKWrQx12jNMX+ZSunQ/PG/4b2IHUsImMQFgLy0o6POgYEalehuagdtnnl9nqWQTyZZozg+4Zm7BRjU/Z1AXGGRdKU1p+Gvfc2rHEA3sn6y0hvZXWp2SKzJtH27QC3dx64IFZ9RhhzL2k=
    POSTGRES_USER: AgBjYRAfGlAXDEzKoiuC3xN/2tFC8swv9GEKImH3jGVyyL+bbl5Ugp1xdF8abMAf3+TWHAr9VgRGhFek5GUi+zVPTKslN4nJA99ygmEOFjEw70gJzxYlZ/jVbNpnbIN/FvhA20Vx6LY9oAG4ZO8l2DW8rUnOwbN9Mzj3dS2fxV+8KnvzVTcr5FKzGBN+QCw61wpLXB2fKgfWWotoVpoRqP4FtXg4fjU7Q4DuMa3ed8s6TUXZ38ov7J4j8YrZIR/eAs2ERu6JwCJavY5DO7f4Oxkboq+jt/Jwhvg97NzVw/XyDhG38WR+GR23wbUQ8uUmQ5ArUFBMobzMETO5oTVXp/tCsI9oRFPlFHsfqWqIdpVEvq7buiI5nWSuTg0JsiRdavTDe2thSKClmo5QbNdUAbuX6R1C6sK7NOcLiIla16D94+y9h2dYfBAZdeYyBfa92YpjleYR2S0Z0pQ6i5chBTiosK0a49g1uWHLNKI8WW95USYjp2R+X+6IQlRJsPixTsB5L7XZcCSyi3XSeuW9/sKZqAlTHNpolOeREXMFZmN3Hp0w6kBrpRh1LhHV86dPMi2hmL6Gzb11uMgO/3BObyH17ylLpNgAyfIt3/XB4zjsW3EvZ5avLY6citYgGlsSd0xQs2KPXBAThtiITx38jTc6co/0LajcIgFiASeLJncP73DahWY6Iisxvn3C9E5d5ldB1Kz3DuSC0s4=
  template:
    metadata:
      name: petclinic-db-credentials
      namespace: pre-sit
